apiVersion: v2
appVersion: "1.0"
description: A Helm chart for pcq-backend App
name: pcq-backend
home: https://github.com/hmcts/pcq-backend
version: 1.1.20
maintainers:
  - name: HMCTS Platform engineering team
dependencies:
  - name: java
    version: 5.2.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
